Sprint 1/step 1
volk-r/react-burger pull request #1
Opened 2023-05-01 10:43 UTC by volk-r

2023-05-01 12:30 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Проект соответствует макету
- Хороший codestyle
- Хорошая декомпозиция компонентов

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Ограничьте ширину блока со списком ингредиентов - иначе он расширяется вместе со страницей

  <img width="538" alt="Снимок экрана 2023-05-01 в 15 23 46" src="https://user-images.githubusercontent.com/60173362/235451209-5bfdc54d-40a1-4622-8f06-f2991fe0888c.png"> 

- для всех необходимых для отображения компонента пропсов в propTypes должен задаваться .isRequired
- Все компоненты с пропсами должны иметь `propTypes`
- Распишите тип ингредиента и используйте везде где в пропсах приходят ингредиенты
- Элементы хедера должны быть ссылками, а не просто текстом. Сейчас можно использовать просто тег `<a/>`.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-01 12:30 UTC, andryxxa93 commented on src/components/app/app.tsx
> +class App extends React.Component {
**Можно лучше**
сейчас при разработке на React стремятся отдавать предпочтение функциональным компонентам, эти компоненты в проекте можно легко переписать как функциональные с использованием хуков

2023-05-01 12:30 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +    _id: PropTypes.string,
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2023-05-01 12:30 UTC, andryxxa93 commented on src/components/burger-ingredients-list/burger-ingredients-list.js
> +export default function BurgerIngredientsList(props) {
**Надо исправить**

для этого компонента так же нужно описать PropTypes

2023-05-01 12:30 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.js
> +    const [current, setCurrent] = React.useState('one')
**Можно лучше**
По дефолту у вас стоит `one` хотя таба с таким `value` нет

2023-05-01 12:30 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.js
> +    data: PropTypes.array
**Необходимо исправить**
Сейчас получается, что под `data` может прийти массив любого содержания, но это не так. Необходимо полностью расписать тип ингредиента со всеми его полями (чтобы не дублировать код - сделайте это в отдельном файле) и использовать во всех подобных местах. Вам помогут в этом функции propTypes `arrayOf` и `shape`.

2023-05-01 17:42 UTC, volk-r commented on src/components/app/app.tsx
> +class App extends React.Component {
fixed

2023-05-01 17:43 UTC, volk-r commented on src/components/burger-ingredients/burger-ingredients.js
> +    const [current, setCurrent] = React.useState('one')
fixed

2023-05-01 18:51 UTC, volk-r commented on src/components/burger-ingredients/burger-ingredients.js
> +    data: PropTypes.array
fixed

2023-05-01 18:51 UTC, volk-r commented on src/components/burger-ingredients-list/burger-ingredients-list.js
> +export default function BurgerIngredientsList(props) {
fixed

2023-05-01 18:51 UTC, volk-r commented on src/components/burger-constructor/burger-constructor.js
> +    _id: PropTypes.string,
done

2023-05-01 18:57 UTC, volk-r commented
исправил замечания

у меня вопрос по проекту, при загрузке вылетает ошибка, при этом проект собирается и работает, наставник предложил переписать на функциональный компонент, но это ровным счет ничего не изменило, при это если закрыть это окно, то все работает без нареканий, в файле ошибок тоже не видно, пробовать переписывать его по всякому, может быть такое из-за расширения файла?

Compiled with problems:

ERROR
[eslint] 
src/app/app.tsx
  Line 8:4:  Parsing error: ')' expected

2023-05-02 09:37 UTC, andryxxa93 approved these changes
Супер, вы отлично потрудились!

**Необходимо исправить**
- `BurgerIngredientsList` добавьте `isRequired`

Промежуточная работа принята, вы можете приступать к финальному этапу сдачи работы!

2023-05-02 09:37 UTC, andryxxa93 commented on src/components/burger-ingredients-list/burger-ingredients-list.js
> +    burgerAttributes: PropTypes.exact(burgerAttributes)
**Можно лучше**
Можно использовать ещё `shape` вместо `exact`

2023-05-02 09:37 UTC, andryxxa93 commented on src/components/burger-ingredients-list/burger-ingredients-list.js
> +    burgerAttributes: PropTypes.exact(burgerAttributes)
**Необходимо исправить**
Тут надо добавить `isRequired`
`    burgerAttributes: PropTypes.exact(burgerAttributes).isRequired`

2023-05-02 09:44 UTC, volk-r commented on src/components/burger-ingredients-list/burger-ingredients-list.js
> +    burgerAttributes: PropTypes.exact(burgerAttributes)
done

2023-05-04 16:42 UTC, merged