Sprint 3/step 1
volk-r/react-burger pull request #5
Opened 2023-06-07 18:56 UTC by volk-r

Проект. Роутинг в React приложении. Реализация механизмов авторизации в React приложении.

2023-06-07 21:08 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Реализовали обновление токена
- Настроены все редиректы
- Хорошая работа с формами

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Не нужно делать запрос данных юзера если в хранилище нет токена

- <img width="1440" alt="Снимок экрана 2023-06-08 в 00 01 07" src="https://github.com/volk-r/react-burger/assets/60173362/e2135100-544c-4571-b88a-6ff172a01064">

- Если изменить только имя или имейл и не трогать пароль, то он всё равно попадает в `payload`, но в не корректном виде

<img width="1397" alt="Снимок экрана 2023-06-08 в 00 02 21" src="https://github.com/volk-r/react-burger/assets/60173362/6d4e7c42-b003-458c-bd7c-b48923d6c596">

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-06-07 21:08 UTC, andryxxa93 commented on src/components/app/app.tsx
> +                    <Route path="/" element={<HomePage />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-06-07 21:08 UTC, andryxxa93 commented on src/pages/register/index.js
> +    const onChange = e => {
**Можно лучше**

Можно сделать универсальный **кастомный** хук для контроля любого количества инпутов в любых формах:
```js
 export function useForm(inputValues) {
   const [values, setValues] = useState(inputValues);
 
   const handleChange = (event) => {
     const {value, name} = event.target;
     setValues({...values, [name]: value});
   };
   return {values, handleChange, setValues};
 }
```
    
Этот код помещают в отдельный файл `useForm.js` в папке `hooks` и импортируют функцию туда, где нужно контролировать инпуты

 И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:
    
 ```js
   const {values, handleChange, setValues} = useForm({});
 ```

2023-06-07 21:08 UTC, andryxxa93 commented on src/pages/register/index.js
> +    if (user) {
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-06-08 13:59 UTC, volk-r commented
@andryxxa93

убрал пароль из изменяемых данных, в ТЗ не описано никаких эндпоинтов для смены пароля, вообще само поле не функционально, зачем оно присутствует в  фигме на данный момент непонятно

наставник ничего внятного не сказал на этот счет

2023-06-08 14:00 UTC, volk-r commented
@andryxxa93 еще у меня вылетает трейс время от времени, не знаю как это поправить https://s.mail.ru/jKZs/57ZtwsSBz

2023-06-08 14:17 UTC, volk-r commented on src/components/app/app.tsx
> +                    <Route path="/" element={<HomePage />} />
fixed

2023-06-08 14:38 UTC, volk-r commented on src/pages/register/index.js
> +    const onChange = e => {
done

2023-06-08 16:47 UTC, volk-r commented on src/pages/register/index.js
> +    if (user) {
done

только передавать path показалось лишним, кажется, что флага вполне хватает

2023-06-09 06:18 UTC, andryxxa93 commented
**Необходимо исправить**
- Поле password должно попадать в `payload` запроса (patch) на изменение данных юзера. Просто у вас если его не трогать, то оно всё равно попадало и имело в себе значение - "***********". Т.е. попадало вот это зашифрованное значение из плейсхолдера инпута и пароль у юзера менялся на некорректный. Вам нужно вернуть поле `password` в payload запроса, но только если юзер внёс изменения в инпут `password`.

2023-06-09 06:19 UTC, andryxxa93 commented
> @andryxxa93 еще у меня вылетает трейс время от времени, не знаю как это поправить https://s.mail.ru/jKZs/57ZtwsSBz https://s.mail.ru/E6NX/Sk2BJT6wy

Это warning  - не ошибка, пока можно не обращать внимания.

2023-06-09 06:40 UTC, volk-r commented
надеюсь, верно истолковал правку по паролю

2023-06-09 07:02 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-06-10 11:59 UTC, merged