Проект. Покрытие приложения тестами
volk-r/react-burger pull request #8
Opened 2023-07-24 17:20 UTC by volk-r

здравствуйте, тесты сделал

а вот с деплоем приложения есть сложности, кто может наставить меня на пусть истинный? настроил все по инструкции, пути прописал, бил скопировал, мб не туда рою

2023-07-24 17:42 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Все редьюсеры покрыты тестами
- Использовали `baseUrl` для cypress
- Для одного теста использовали один expect - это хорошая практика

Необходимо исправить:
- Ссылка на деплой ведёт на пустой сайт. Обратитесь пожалуйста к своему наставнику.

- Cypress тесты не запускаются, возможно не все файлы настройки попали в коммит.
 <img width="971" alt="Снимок экрана 2023-07-24 в 20 37 53" src="https://github.com/volk-r/react-burger/assets/60173362/e43dfaa9-c1d4-44f9-bf93-cd35ae19b1d5">

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-24 17:56 UTC, volk-r commented
@andryxxa93 

по тестам cypress

у меня 2 файла

1. cypress/e2e/integration/home-page.cy.ts - https://github.com/volk-r/react-burger/pull/8/files#diff-80c9b2b28071ded2dbe413976251ee35900a1e4b1444614efd3f0946d9d60121 https://cloud.mail.ru/public/BizF/MRMKgqfcy
2. cypress/e2e/integration/is-available.cy.ts - https://github.com/volk-r/react-burger/pull/8/files#diff-095583c8026c4584c5ceed5fc8780fc60887d5a6f2481bfde5fc0157254c5a0c https://cloud.mail.ru/public/cwxB/QXVvUzikm

никаких ошибок не наблюдаю, только что запустил еще раз, оба работают, мб у нас разные версии или настройки?

2023-07-24 18:02 UTC, volk-r commented
добавил еще эти

1. fixtures
2. support

https://cloud.mail.ru/public/L3DW/fCZSx3HrU

2023-07-25 14:58 UTC, volk-r commented
С деплоем разобрался, еще один баг попутно обнаружил, вылез после деплоя, локально практически не воспроизводился

2023-07-26 09:57 UTC, andryxxa93 commented
Супер! `Jest` тесты и `Cypress` настроены и работают верно. 
Работа принята. Удачи вам и успехов!

2023-07-26 09:59 UTC, volk-r commented
@andryxxa93 благодарю!

2023-07-26 09:59 UTC, merged